### ISSUE TITLE
task list (check list) is not rendered properly

### ISSUE THREAD

**Issue by yech1990** [AmazingRise/hugo-theme-diary#4] opened 2020-01-30 10:09 UTC
```
- [X] task1
- [ ] task2 
```

**Comment by AmazingRise** [comment] 2020-01-31 14:21
Thanks for the issue.
In fact, it is a default behavior, again.
Hugo will add an `<li>` to every task list item. That produces an ugly big black circle point.

Take your test case as example, the final rendering result is:
```html
<ul>
<li><input checked="" disabled="" type="checkbox">task1</li>
<li><input disabled="" type="checkbox">task2</li>
</ul>
```
My Hugo version is `Hugo Static Site Generator v0.63.2/extended linux/amd64`.
The most difficult point is, I can't define the style of `<ul> <li>` in task list seperately. If I define them in CSS, normal list will also be influenced.

Interestingly, I found a [3rd-party Hugo tutorial](https://bwaycer.github.io/hugo_tutorial.hugo/content/markdown-extras/), and the `<ul>` in this case is with a class named `task-list`. But I can't reproduce in my environment. Maybe a deprecated feature in old version?

Furthermore, I checked the implementation in other themes. No implementations at all 😂️.
So I think this issue could be raised to Hugo official - let them add a class property to task list's `ul`, so we can define the style.

**Comment by AmazingRise** [comment] 2020-01-31 14:44
I did a further search.

I searched `task-list` in [Hugo source code](https://github.com/gohugoio/hugo/search?q=task-list&unscoped_q=task-list), and found that only in `blackfriday`, the old default markdown renderer, can produce a `ul` with `task-list` class.

I set `defaultMarkdownHandler` to `blackfriday` in my top level `config.toml`:
```toml
[markup]
defaultMarkdownHandler = "blackfriday"
```
And as expected, I got a `<ul>` with `task-list` class attached.
```html
<ul class="task-list">
<li><label><input type="checkbox" checked="" disabled="" class="task-list-item"> task1</label></li>
<li><label><input type="checkbox" disabled="" class="task-list-item"> task2</label></li>
</ul>
```
So thanks for raising this problem, and I will open the issue on Hugo's official repository.

And please don't close this issue. I will add it back as soon as Hugo official fix this issue.

**Comment by AmazingRise** [comment] 2020-02-02 14:04
Closed. The author of goldmark didn't approve this feature.

**Closed by AmazingRise** 2020-02-02 14:04 UTC
Labels: enhancement
